name: Docker Build

run-name: Docker Build:${{ github.ref_name }}(${{ github.event.head_commit.message }})

on:
  push:

env:
  platforms: linux/amd64, linux/arm64/v8

jobs:
  docker-build:
    runs-on: ubuntu-22.04

    permissions:
      packages: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
          logout: false

      - name: Extract metadata (tags, labels) for Docker
        id: set-docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.platforms }}

      - name: Set up Docker Buildx
        id: set-docker-builder
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.platforms }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.set-docker-metadata.outputs.tags }}
          labels: ${{ steps.set-docker-metadata.outputs.labels }}
          platforms: ${{ inputs.platforms }}
          builder: ${{ steps.set-docker-builder.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha, mode=max